config/routes.rb
Rails.application.routes.draw do
  resources :servings
  resources :food_items
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :serving_category
end

app/models/serving.rb
class Serving < ApplicationRecord
  has_one :serving_category
  has_one :food_item
end

app/models/serving_category.rb
class ServingCategory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/food_item_controller.rb
class FoodItemController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'FoodItem was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Serving was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Serving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :category_id, :notes)
    end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'FoodItem was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Serving was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Serving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :category_id, :notes)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/servings_controller.rb
class ServingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_serving, only: [:show, :edit, :update, :destroy]

  # GET /servings
  # GET /servings.json
  def index
    @servings = Serving.all
  end

  # GET /servings/1
  # GET /servings/1.json
  def show
  end

  # GET /servings/new
  def new
    @serving = Serving.new
  end

  # GET /servings/1/edit
  def edit
  end

  # POST /servings
  # POST /servings.json
  def create
    @serving = Serving.new(serving_params)

    respond_to do |format|
      if @serving.save
        format.html { redirect_to @serving, notice: 'Serving was successfully created.' }
        format.json { render :show, status: :created, location: @serving }
      else
        format.html { render :new }
        format.json { render json: @serving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servings/1
  # PATCH/PUT /servings/1.json
  def update
    respond_to do |format|
      if @serving.update(serving_params)
        format.html { redirect_to @serving, notice: 'Serving was successfully updated.' }
        format.json { render :show, status: :ok, location: @serving }
      else
        format.html { render :edit }
        format.json { render json: @serving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servings/1
  # DELETE /servings/1.json
  def destroy
    @serving.destroy
    respond_to do |format|
      format.html { redirect_to servings_url, notice: 'Serving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serving
      @serving = Serving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def serving_params
      params.require(:serving).permit(:day, :serving_category_id, :food_item_id, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_item_helper.rb
module FoodItemHelper
end

app/helpers/servings_helper.rb
module ServingsHelper
end

app/views/food_items/create.html.haml
%h1 FoodItem#create
%p Find me in app/views/food_item/create.html.haml

app/views/food_items/destroy.html.haml
%h1 FoodItem#destroy
%p Find me in app/views/food_item/destroy.html.haml

app/views/food_items/edit.html.haml
%h1 FoodItem#edit
%p Find me in app/views/food_item/edit.html.haml

app/views/food_items/index.html.haml
%h1 FoodItem#index
%p Find me in app/views/food_item/index.html.haml

app/views/food_items/new.html.haml
%h1 FoodItem#new
%p Find me in app/views/food_item/new.html.haml

app/views/food_items/show.html.haml
%h1 FoodItem#show
%p Find me in app/views/food_item/show.html.haml

app/views/food_items/update.html.haml
%h1 FoodItem#update
%p Find me in app/views/food_item/update.html.haml

app/views/home/index.html.haml
%h1 Veggie Up!
%p Set and track goals for healthy eating.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veggieup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/servings/_form.html.haml
= form_for @serving do |f|
  - if @serving.errors.any?
    #error_explanation
      %h2= "#{pluralize(@serving.errors.count, "error")} prohibited this serving from being saved:"
      %ul
        - @serving.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :day
    = f.date_select :day
  .field
    = f.label :serving_category
    = f.number_field :serving_category_id
  .field
    = f.label :food_item
    = f.number_field :food_item_id
  .field
    = f.label :notes
    = f.text_area :notes
  .actions
    = f.submit 'Save'

app/views/servings/edit.html.haml
%h1 Editing serving

= render 'form'

= link_to 'Show', @serving
\|
= link_to 'Back', servings_path

app/views/servings/index.html.haml
%h1 Listing servings

%table
  %thead
    %tr
      %th Day
      %th Category
      %th Food item
      %th Notes
      %th
      %th
      %th

  %tbody
    - @servings.each do |serving|
      %tr
        %td= serving.day
        %td= serving.serving_category
        %td= serving.food_item
        %td= serving.notes
        %td= link_to 'Show', serving
        %td= link_to 'Edit', edit_serving_path(serving)
        %td= link_to 'Destroy', serving, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Serving', new_serving_path

app/views/servings/new.html.haml
%h1 New serving

= render 'form'

= link_to 'Back', servings_path

app/views/servings/show.html.haml
%p#notice= notice

%p
  %b Day:
  = @serving.day
%p
  %b Category:
  = @serving.category
%p
  %b Food item:
  = @serving.food_item
%p
  %b Notes:
  = @serving.notes

= link_to 'Edit', edit_serving_path(@serving)
\|
= link_to 'Back', servings_path